# Nama situs
title: domen

# Deskripsi situs
description: pengujian
# URL dasar
url: https://eternalsya.github.io

# Base URL (jika perlu, biasanya untuk repositori yang bukan di root)
baseurl: /domen

# Tema yang digunakan
theme: minima  # atau tema lain yang lo pilih

# Penulis
author:
  name: EternalsYa
  email: databaseszyn@gmail.com

# Pengaturan lain
markdown: kramdown
permalink: pretty
